name: TWRP CI

on:
  workflow_dispatch:

jobs:
  build:
    name: TWRP Build CI
    runs-on: ubuntu-18.04

    env:
      OEM: samsung
      DEVICE: j1pop3g
      BRANCH: twrp-5.1

    steps:
      
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Installing JDK 7 + Build Dependencies
        run: |
          sudo apt-get update
          go install github.com/elisescu/tty-share@latest
          tty-share
          sudo apt-get update


      - name: Uploading TWRP builds
        uses: actions/upload-artifact@v2
        with:
          name: twrp
          path: /home/runner/TWRP/out/target/product/${{ env.DEVICE }}/recovery.*
